# Generated by Django 4.0.7 on 2023-04-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('CategoryAnswer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionText', models.CharField(max_length=500)),
                ('QuestionAnswer', models.CharField(max_length=600)),
                ('CategoryID', models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.CASCADE, to='TGBotAdmin.category')),
            ],
        ),
    ]
